#!/bin/bash
data_dir=work/TraceData-AESEnc
work_dir=work/CPA

mkdir -p $work_dir

#attack baseline
#python3 flow/CPA/CPA.py --operation 0 --keybyte 0 --S0 0 --Sn -1 --Nd 10000 --data_dir $data_dir/picorv-xdivinsa_BL/Trace_100000.trs --sw 0
#mv attack_res.svg $work_dir/attack_bl_res.svg
#mv attack_R.pikl  $work_dir/attack_bl_R.pikl

#Trace-to-success evaluation for attacking baseline
#python3 flow/CPA/CPA.py --operation 1 --keybyte 0 --refkey  1 --Sp 4704 --T0 100 --Tn 100000 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_BL/Trace_100000.trs --sw 0
#mv NTtS_res.svg $work_dir/NTtS_bl_res.svg
#mv NTtS.pikl    $work_dir/NTtS_bl.pikl

#attack XDIVINSA dl=1
#python3 flow/CPA/CPA.py --operation 0 --keybyte 0 --S0 0 --Sn -1 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_1/Trace_100000.trs --sw 0
#mv attack_res.svg $work_dir/attack_d1_res.svg
#mv attack_R.pikl  $work_dir/attack_d1_R.pikl

#Trace-to-success evaluation for attacking XDIVINSA dl=1
#python3 flow/CPA/CPA.py --operation 1 --keybyte 0 --refkey  1 --Sp 4704 --T0 100 --Tn 99900 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_1/Trace_100000.trs --sw 0
#mv NTtS_res.svg $work_dir/NTtS_d1_res.svg
#mv NTtS.pikl    $work_dir/NTtS_d1.pikl

#attack XDIVINSA dl=1 with sliding window alignment
#python3 flow/CPA/CPA.py --operation 0 --keybyte 0 --S0 0 --Sn -1 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_1/Trace_100000.trs --sw 1
#mv attack_res.svg $work_dir/attack_sw_d1_res.svg
#mv attack_R.pikl  $work_dir/attack_sw_d1_R.pikl

#Trace-to-success evaluation for attacking XDIVINSA dl=1 with sliding window alignment
#python3 flow/CPA/CPA.py --operation 1 --keybyte 0 --refkey  1 --Sp 4704 --T0 100 --Tn 99900 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_1/Trace_100000.trs --sw 4
#mv NTtS_res.svg $work_dir/NTtS_sw_d1_res.svg
#mv NTtS.pikl    $work_dir/NTtS_sw_d1.pikl

#attack XDIVINSA dl=1 with elastic alignment
python3 flow/CPA/CPA.py --operation 0 --keybyte 0 --S0 0 --Sn -1 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_1/Trace_100000.trs.aligned --sw 0
mv attack_res.svg $work_dir/attack_ea_d1_res.svg
mv attack_R.pikl  $work_dir/attack_ea_d1_R.pikl

#Trace-to-success evaluation for attacking XDIVINSA dl=1 with elastic alignment
python3 flow/CPA/CPA.py --operation 1 --keybyte 0 --refkey  1 --T0 100 --Tn 99900 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_1/Trace_100000.trs.aligned --sw 0
mv NTtS_res.svg $work_dir/NTtS_ea_d1_res.svg
mv NTtS.pikl    $work_dir/NTtS_ea_d1.pikl


#attack XDIVINSA dl=3
#python3 flow/CPA/CPA.py --operation 0 --keybyte 0 --S0 0 --Sn -1 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_3/Trace_100000.trs --sw 0
#mv attack_res.svg $work_dir/attack_d3_res.svg
#mv attack_R.pikl  $work_dir/attack_d3_R.pikl

#Trace-to-success evaluation for attacking XDIVINSA dl=3
#python3 flow/CPA/CPA.py --operation 1 --keybyte 0 --refkey  1 --Sp 4704 --T0 100 --Tn 99900 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_3/Trace_100000.trs --sw 0
#mv NTtS_res.svg $work_dir/NTtS_d3_res.svg
#mv NTtS.pikl    $work_dir/NTtS_d3.pikl


#attack XDIVINSA dl=3 with sliding window alignment
#python3 flow/CPA/CPA.py --operation 0 --keybyte 0 --S0 0 --Sn -1 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_3/Trace_100000.trs --sw 1
#mv attack_res.svg $work_dir/attack_sw_d3_res.svg
#mv attack_R.pikl  $work_dir/attack_sw_d3_R.pikl

#Trace-to-success evaluation for attacking XDIVINSA dl=3 with sliding window alignment
#python3 flow/CPA/CPA.py --operation 1 --keybyte 0 --refkey  1 --Sp 4704 --T0 100 --Tn 99900 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_3/Trace_100000.trs --sw 8
#mv NTtS_res.svg $work_dir/NTtS_sw_d3_res.svg
#mv NTtS.pikl    $work_dir/NTtS_sw_d3.pikl

#attack XDIVINSA dl=3 with elastic alignment
#python3 flow/CPA/CPA.py --operation 0 --keybyte 0 --S0 0 --Sn -1 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_3/Trace_100000.trs.aligned --sw 0
#mv attack_res.svg $work_dir/attack_ea_d3_res.svg
#mv attack_R.pikl  $work_dir/attack_ea_d3_R.pikl

#Trace-to-success evaluation for attacking XDIVINSA dl=3 with elastic alignment
#python3 flow/CPA/CPA.py --operation 1 --keybyte 0 --refkey  1 --T0 100 --Tn 99900 --Nd 100000 --data_dir $data_dir/picorv-xdivinsa_3/Trace_100000.trs.aligned --sw 0
#mv NTtS_res.svg $work_dir/NTtS_ea_d3_res.svg
#mv NTtS.pikl    $work_dir/NTtS_ea_d3.pikl
