#!/bin/bash
export PORT=/dev/ttyUSB0
export BAUD=115200   
#export BAUD=57600
#export FREQ=25M
export NUM_TRACES=1000000
export T_FUNC=XdiAdd

export CORE=picorv-xdivinsa


IMPL_V="d0"
XD_V="1 2 3 4 5"

echo $CORE
echo $T_FUNC

#sed -i 's/^.* import SAFTFunc$/from .SAFTFunc_ModExp       import SAFTFunc/g'  ${SASS_RIG}/sassrig/SAFShell.py
sed -i 's/^scope_cfg_trace_channel.*/scope_cfg_trace_channel A/g' ${XDI_HOME}/flow/acquisition/gather-t-func-${T_FUNC}-ttest.txt
#sed -i 's/^t_func_ttest_acq.*/t_func_ttest_acq 250e6 210000 8 $NUMTR $XDI_HOME\/work\/tt_set1.trs $XDI_HOME\/work\/tt_set2.trs/g'  ${XDI_HOME}/flow/acquisition/gather-t-func-ttest.txt


#for I in $IMPL_V; do
#    make verilog IMPL=$I
#    echo "Implementing bitstream of design for FPGA ..."
#    make bitstream > /dev/null

#echo "For Xdivinsa $XD_V ..."
#for T in $XD_V; do
#    mkdir -p ${XDI_HOME}/work/TTestData-XdiAdd/TTest_${CORE}_t${T,,}
#    make -B sass-xdiadd XD="-DXDIVINSA=$T" 
#    make program-fpga
#    make t-func-verify PORT=$PORT BAUD=$BAUD T_FUNC=$T_FUNC 
#    make t-func-ttest  PORT=$PORT BAUD=$BAUD T_FUNC=$T_FUNC NUM_TRACES=$NUM_TRACES
#    mv ${XDI_HOME}/work/tt_set1.trs ${XDI_HOME}/work/TTestData-XdiAdd/TTest_${CORE}_t${T,,}/tt_set1_${NUM_TRACES}.trs
#    mv ${XDI_HOME}/work/tt_set2.trs ${XDI_HOME}/work/TTestData-XdiAdd/TTest_${CORE}_t${T,,}/tt_set2_${NUM_TRACES}.trs
#    mv ${XDI_HOME}/work/tt.svg      ${XDI_HOME}/work/TTestData-XdiAdd/TTest_${CORE}_t${T,,}/TTest_${CORE}_t${T,,}_${NUM_TRACES}.svg
#done

echo "For Baseline ..."
mkdir -p ${XDI_HOME}/work/TTestData-XdiAdd/TTest_${CORE}_BL
make -B sass-xdiadd XD= > /dev/null
make program-fpga
make t-func-verify PORT=$PORT BAUD=$BAUD
	make t-func-ttest  PORT=$PORT BAUD=$BAUD NUM_TRACES=$NUM_TRACES
mv ${XDI_HOME}/work/tt_set1.trs ${XDI_HOME}/work/TTestData-XdiAdd/TTest_${CORE}_BL/tt_set1_${NUM_TRACES}.trs
mv ${XDI_HOME}/work/tt_set2.trs ${XDI_HOME}/work/TTestData-XdiAdd/TTest_${CORE}_BL/tt_set2_${NUM_TRACES}.trs
mv ${XDI_HOME}/work/tt.svg      ${XDI_HOME}/work/TTestData-XdiAdd/TTest_${CORE}_BL/TTest_${CORE}_BL_${NUM_TRACES}.svg

