#!/bin/bash
export PORT=/dev/ttyUSB0
#export BAUD ?= 115200   
export BAUD=57600
export FREQ=25M
export NUMTR=50000
export INTYPE=nonzero


export CORE=rocket-xdivinsa-$FREQ

PREPRO_V="None"
IMPL_V="d0"
XD_V=" T0  T1  T2  T3  T4"
S0_V=(  0   0   0   0   0)
#SN_V=(400 420 460 540)
SN_V=(700 700 700 700 700)
NT_V="5000"
echo $CORE
#mkdir -p ${BSX_HOME}/work/TTestData

for P in $PREPRO_V; do
    echo "Using $P technique for preprocessing"
    echo "For Xdivinsa ..."
    echo "TTest Report " > ttest-eval-$P.rpt
    cnt=0    
    for I in $IMPL_V; do
        echo $I >> ttest-eval-$P.rpt
        for T in $XD_V; do
            echo '   '$T >> ttest-eval-$P.rpt
            echo '   '$NT_V >> ttest-eval-$P.rpt
            ttestmax=''
            for N in $NT_V; do
                ST='s/^t_func_ttest_eval.*/t_func_ttest_eval '
                ST+=${N}' '${S0_V[$cnt]}' '${SN_V[$cnt]}' '$P' '
                ST+='$BSX_HOME\/work\/TTestDataRef1\/TTest_25M_xdivinsa_'${I}${T,,}'_nonzero\/tt_set1_10000.trs '
                ST+='$BSX_HOME\/work\/TTestDataRef1\/TTest_25M_xdivinsa_'${I}${T,,}'_nonzero\/tt_set2_10000.trs '
                ST+='$BSX_HOME\/work\/TTestDataRef1\/TTest_25M_xdivinsa_'${I}${T,,}'_nonzero\/tt_'${P}'_'${N}'.svg '
                ST+='$BSX_HOME\/work\/TTestDataRef1\/TTest_25M_xdivinsa_'${I}'d'${T,,}'_nonzero\/tt_set1_10000.trs/g'
                sed -i "${ST}" ${XDI_HOME}/flow/acquisition/ttest-eval.txt        
                #tem=($(make t-func-ttest-eval | grep ^'Max-value:'))
                make t-func-ttest-eval
                ttestmax+=' '${tem[1]:0:5}
            done
            echo '  '$ttestmax >> ttest-eval-$P.rpt 
            cnt=$(( $cnt + 1 ))
        done
    done
    echo "For Baseline ..."
done
