#!/bin/bash
export PORT=/dev/ttyUSB0
export BAUD=115200   
#export BAUD=57600
export FREQ=25M
export NUMTR=20
export INTYPE=nonzero
export T_FUNC=ModExp

export CORE=rocket-xdivinsa
export ALG="SF"

IMPL_V="d0"
XD_V="T0 T1"

echo $CORE
echo $T_FUNC
#sed -i 's/^.* import SAFTFunc$/from .SAFTFunc_ModExp       import SAFTFunc/g'  ${SASS_RIG}/sassrig/SAFShell.py
sed -i 's/^scope_cfg_trace_channel.*/scope_cfg_trace_channel B/g' ${XDI_HOME}/flow/acquisition/gather-t-func-ttest.txt
#sed -i 's/^t_func_ttest_acq.*/t_func_ttest_acq 125e6 4700000 8 $NUMTR $XDI_HOME\/work\/tt_set1.trs $XDI_HOME\/work\/tt_set2.trs/g'  ${XDI_HOME}/flow/acquisition/gather-t-func-ttest.txt

echo "For Xdivinsa ..."
for I in $IMPL_V; do
#    make verilog IMPL=$I
    echo "Implementing bitstream of design for FPGA ..."
    make bitstream > /dev/null
    for T in $XD_V; do
        mkdir -p ${XDI_HOME}/work/TTestData-ModExp-$ALG/TTest_${CORE}_${I}${T,,}
        make -B sass-modexp XD="-DXDIVINSA -DXDIVINSA_$T" > /dev/null
        make program-fpga
        make t-func-verify PORT=$PORT BAUD=$BAUD
        make t-func-ttest  PORT=$PORT BAUD=$BAUD
        mv ${XDI_HOME}/work/tt_set1.trs ${XDI_HOME}/work/TTestData-ModExp-$ALG/TTest_${CORE}_${I}${T,,}/tt_set1_${NUMTR}.trs
        mv ${XDI_HOME}/work/tt_set2.trs ${XDI_HOME}/work/TTestData-ModExp-$ALG/TTest_${CORE}_${I}${T,,}/tt_set2_${NUMTR}.trs
        mv ${XDI_HOME}/work/tt.svg      ${XDI_HOME}/work/TTestData-ModExp-$ALG/TTest_${CORE}_${I}${T,,}/TTest_${CORE}_${I}${T,,}_${NUMTR}.svg
    done
done

echo "For Baseline ..."
mkdir -p ${XDI_HOME}/work/TTestData-ModExp-$ALG/TTest_${CORE}_BL
make -B sass-modexp XD=
make program-fpga
make t-func-verify PORT=$PORT BAUD=$BAUD
make t-func-ttest  PORT=$PORT BAUD=$BAUD
mv ${XDI_HOME}/work/tt_set1.trs ${XDI_HOME}/work/TTestData-ModExp-$ALG/TTest_${CORE}_BL/tt_set1_${NUMTR}.trs
mv ${XDI_HOME}/work/tt_set2.trs ${XDI_HOME}/work/TTestData-ModExp-$ALG/TTest_${CORE}_BL/tt_set2_${NUMTR}.trs
mv ${XDI_HOME}/work/tt.svg      ${XDI_HOME}/work/TTestData-ModExp-$ALG/TTest_${CORE}_BL/TTest_${CORE}_BL_${NUMTR}.svg


