#!/bin/bash

export T_FUNC=XdiAdd 
export CORE=picorv-xdivinsa


IMPL_V="d0"
XD_V="  1   2   3  "
S0_V=( 25  25  25  25  25)
#SN_V=(400 420 460 540)
SN_V=(170 170 170 170 170)
NT_V="100000"
NT="1000000"
echo $CORE
#mkdir -p ${XDI_HOME}/work/TTestData

 
echo "For Xdivinsa ..."
cnt=0 
for T in $XD_V; do
    for N in $NT_V; do
        ST='s/^t_func_ttest_eval.*/t_func_ttest_eval '
        ST+=${N}' '${S0_V[$cnt]}' '${SN_V[$cnt]}' None '
        ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_t'${T}'\/tt_set1_'${NT}'.trs '
        ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_t'${T}'\/tt_set2_'${NT}'.trs '
        ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_t'${T}'\/tt_plot_'${N}'.svg '
        ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_t'${T}'\/tt_set1_'${NT}'.trs/g'
        sed -i "${ST}" ${XDI_HOME}/flow/acquisition/ttest-eval.txt        
        make t-func-ttest-eval
    done
    cnt=$(( $cnt + 1 ))
done

#echo "For CIDPro ..."
#ST='s/^t_func_ttest_eval.*/t_func_ttest_eval '
#ST+=${N}' '${S0_V[0]}' '${SN_V[0]}' None '
#ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_CIDPro\/tt_set1_'${N}'.trs '
#ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_CIDPro\/tt_set2_'${N}'.trs '
#ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_CIDPro\/tt_plot_'${N}'.svg '
#ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_CIDPro\/tt_set1_'${N}'.trs/g'
#sed -i "${ST}" ${XDI_HOME}/flow/acquisition/ttest-eval.txt        
#make t-func-ttest-eval

echo "For Baseline ..."
ST='s/^t_func_ttest_eval.*/t_func_ttest_eval '
ST+='100000 25 170 None '
ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_BL\/tt_set1_1M.trs '
ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_BL\/tt_set2_1M.trs '
ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_BL\/tt_plot_'${N}'.svg '
ST+='$XDI_HOME\/work\/TTestData-'${T_FUNC}'\/TTest_'${CORE}'_BL\/tt_set1_1M.trs/g'
sed -i "${ST}" ${XDI_HOME}/flow/acquisition/ttest-eval.txt        
make t-func-ttest-eval
