#!/bin/bash
export PORT=/dev/ttyUSB0
export BAUD=115200   
#export BAUD=57600
#export FREQ=25M
export NUM_TRACES=100000
export T_FUNC=AESEnc

export CORE=picorv-xdivinsa

IMPL_V="d0 d3"

echo $CORE
echo $T_FUNC


sed -i 's/^scope_cfg_trace_channel.*/scope_cfg_trace_channel A/g' ${XDI_HOME}/flow/acquisition/gather-t-func-${T_FUNC}-traces.txt

echo "For Xdivinsa ..."
XD_V="4"
for T in $XD_V; do
    mkdir -p ${XDI_HOME}/work/TraceData-AESEnc/${CORE}_${T,,}
    make -B sass-aes-enc XD="-DXDIVINSA=$T"
    make program-fpga
    make t-func-verify PORT=$PORT BAUD=$BAUD T_FUNC=$T_FUNC
    make t-func-traces PORT=$PORT BAUD=$BAUD T_FUNC=$T_FUNC
    mv ${XDI_HOME}/work/traces.trs ${XDI_HOME}/work/TraceData-AESEnc/${CORE}_${T,,}/Trace_${NUM_TRACES}.trs
done


echo "For Baseline ..."
mkdir -p ${XDI_HOME}/work/TraceData-AESEnc/${CORE}_BL
make -B sass-aes-enc XD=" "
make program-fpga
make t-func-verify PORT=$PORT BAUD=$BAUD
make t-func-traces PORT=$PORT BAUD=$BAUD
mv ${XDI_HOME}/work/traces.trs ${XDI_HOME}/work/TraceData-AESEnc/${CORE}_BL/Trace_${NUM_TRACES}.trs


