#!/bin/bash
data_dir=work/TraceData-AESEnc
work_dir=work/CPA

mkdir -p $work_dir

#attack baseline
python3 flow/CPA/Plot_CPAresults.py --operation 0 --ylim 0.15 --datfile $work_dir/attack_bl_R.pikl --svgfile $work_dir/CPA_attack_bl_res.svg
#attack XDIVINSA dl=1
python3 flow/CPA/Plot_CPAresults.py --operation 0 --ylim 0.15 --datfile $work_dir/attack_d1_R.pikl --svgfile $work_dir/CPA_attack_d1_res.svg
#attack XDIVINSA dl=3
python3 flow/CPA/Plot_CPAresults.py --operation 0 --ylim 0.15 --datfile $work_dir/attack_d3_R.pikl --svgfile $work_dir/CPA_attack_d3_res.svg

#Trace-to-success evaluation for attacking baseline
python3 flow/CPA/Plot_CPAresults.py --operation 1 --ylim 0.2 --datfile $work_dir/NTtS_bl.pikl    --svgfile $work_dir/CPA_NTtS_bl_res.svg
#Trace-to-success evaluation for attacking XDIVINSA dl=1
python3 flow/CPA/Plot_CPAresults.py --operation 1 --ylim 0.2 --datfile $work_dir/NTtS_d1.pikl    --svgfile $work_dir/CPA_NTtS_d1_res.svg
#Trace-to-success evaluation for attacking XDIVINSA dl=3
python3 flow/CPA/Plot_CPAresults.py --operation 1 --ylim 0.2 --datfile $work_dir/NTtS_d3.pikl    --svgfile $work_dir/CPA_NTtS_d3_res.svg

#Trace-to-success evaluation for attacking XDIVINSA dl=1 with sliding window alignement
python3 flow/CPA/Plot_CPAresults.py --operation 1 --ylim 0.1 --datfile $work_dir/NTtS_sw_d1.pikl --svgfile $work_dir/CPA_NTtS_sw_d1_res.svg
#Trace-to-success evaluation for attacking XDIVINSA dl=1 with elastic alignement
python3 flow/CPA/Plot_CPAresults.py --operation 1 --ylim 0.1 --datfile $work_dir/NTtS_ea_d1.pikl --svgfile $work_dir/CPA_NTtS_ea_d1_res.svg
#Trace-to-success evaluation for attacking XDIVINSA dl=3 with sliding window alignement
python3 flow/CPA/Plot_CPAresults.py --operation 1 --ylim 0.1 --datfile $work_dir/NTtS_sw_d3.pikl --svgfile $work_dir/CPA_NTtS_sw_d3_res.svg
#Trace-to-success evaluation for attacking XDIVINSA dl=3 with elastic alignement
python3 flow/CPA/Plot_CPAresults.py --operation 1 --ylim 0.1 --datfile $work_dir/NTtS_ea_d3.pikl --svgfile $work_dir/CPA_NTtS_ea_d3_res.svg




